version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB_PASSWORD=yourpassword
  #     - DB_NAME=doqr
  #   depends_on:
  #     - mysql
  #   command: npm run dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: doqr
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: